name: Spotify Playlist Updates

on:
  schedule:
    # Trigger for the daily job (runs at 7:00 and 8:00 UTC)
    - cron: '0 7,8 * * *'
    # MODIFIED: Trigger for the monthly job now runs at both 7:00 and 8:00 UTC on the 1st of the month
    - cron: '0 7,8 1 * *'
  
  workflow_dispatch:
    inputs:
      force_run_daily:
        description: 'Force run the DAILY scripts'
        required: true
        type: boolean
        default: false
      force_run_monthly:
        description: 'Force run the MONTHLY unabridged script'
        required: true
        type: boolean
        default: false

jobs:
  # This job handles your original daily playlist updates
  update-daily-playlists:
    if: (github.event.schedule == '0 7,8 * * *') || (github.event.inputs.force_run_daily == 'true')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Check Time for Daily Run
        id: check_time
        run: |
          python <<EOF
          import os, pytz
          from datetime import datetime
          tz = pytz.timezone('America/Los_Angeles')
          local_time = datetime.now(tz)
          print(f'Current time in {tz} is {local_time.strftime("%Y-%m-%d %H:%M:%S")}')
          should_run = local_time.hour == 0
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              print(f'should_run={str(should_run).lower()}', file=f)
          EOF

      - name: Run On This Day script
        if: (github.event_name == 'schedule' && steps.check_time.outputs.should_run == 'true') || (github.event.inputs.force_run_daily == 'true')
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: python on_this_day.py

      - name: Run Random Day script
        if: (github.event_name == 'schedule' && steps.check_time.outputs.should_run == 'true') || (github.event.inputs.force_run_daily == 'true')
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: python random_day.py

  # This job handles your monthly unabridged playlist update
  update-unabridged-playlist:
    # MODIFIED: The schedule in the 'if' condition is updated to match the dual-hour cron
    if: (github.event.schedule == '0 7,8 1 * *') || (github.event.inputs.force_run_monthly == 'true')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # NEW: Time-check logic is added to the monthly job
      - name: Check Time for Monthly Run
        id: check_time_monthly
        run: |
          python <<EOF
          import os, pytz
          from datetime import datetime
          tz = pytz.timezone('America/Los_Angeles')
          local_time = datetime.now(tz)
          print(f'Current time in {tz} is {local_time.strftime("%Y-%m-%d %H:%M:%S")}')
          should_run = local_time.hour == 0
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              print(f'should_run={str(should_run).lower()}', file=f)
          EOF

      # MODIFIED: The main script step is now conditional
      - name: Run Unabridged script
        if: (github.event_name == 'schedule' && steps.check_time_monthly.outputs.should_run == 'true') || (github.event.inputs.force_run_monthly == 'true')
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: python unabridged.py